<?xml version="1.0" encoding="UTF-8"?>

<!--
  * journalSettings.xml
  *
  * Copyright (c) 2003-2007 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Default journal settings.
  *
  * $Id$
  -->

<!DOCTYPE journal_settings [
	<!ELEMENT journal_settings (setting+)>
	<!ELEMENT setting (name, value)>
	<!ATTLIST setting type (int|string|object|bool) #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT value (#PCDATA | array)*>
	<!ELEMENT element (#PCDATA | array)*>
	<!ATTLIST element key CDATA #IMPLIED>
	<!ELEMENT array (element+)>
]>

<journal_settings>
	<setting type="int">
		<name>numPageLinks</name>
		<value>10</value>
	</setting>
	<setting type="int">
		<name>itemsPerPage</name>
		<value>25</value>
	</setting>
	<setting type="int">
		<name>numWeeksPerReview</name>
		<value>4</value>
	</setting>
	<setting type="string">
		<name>primaryLocale</name>
		<value>{$primaryLocale}</value>
	</setting>
	<setting type="string">
		<name>privacyStatement</name>
		<value>{translate key="default.journalSettings.privacyStatement"}</value>
	</setting>
	<setting type="string">
		<name>openAccessPolicy</name>
		<value>{translate key="default.journalSettings.openAccessPolicy"}</value>
	</setting>
	<setting type="string">
		<name>authorSelfArchivePolicy</name>
		<value>{translate key="default.journalSettings.authorSelfArchivePolicy"}</value>
	</setting>
	<setting type="string">
		<name>copyeditInstructions</name>
		<value>{translate key="default.journalSettings.copyeditInstructions"}</value>
	</setting>
	<setting type="string">
		<name>emailSignature</name>
		<value>{translate key="default.journalSettings.emailSignature"}</value>
	</setting>
	<setting type="string">
		<name>proofInstructions</name>
		<value>{translate key="default.journalSettings.proofingInstructions"}</value>
	</setting>
	<setting type="string">
		<name>readerInformation</name>
		<value>{translate key="default.journalSettings.forReaders"}</value>
	</setting>
	<setting type="string">
		<name>authorInformation</name>
		<value>{translate key="default.journalSettings.forAuthors"}</value>
	</setting>
	<setting type="string">
		<name>librarianInformation</name>
		<value>{translate key="default.journalSettings.forLibrarians"}</value>
	</setting>
	<setting type="string">
		<name>lockssLicense</name>
		<value>{translate key="default.journalSettings.lockssLicense"}</value>
	</setting>
	<setting type="object">
		<name>submissionChecklist</name>
		<value>
			<array>
				<element>
					<array>
						<element key="content">{translate key="default.journalSettings.checklist.notPreviouslyPublished"}</element>
						<element key="order">1</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.journalSettings.checklist.fileFormat"}</element>
						<element key="order">2</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.journalSettings.checklist.addressesLinked"}</element>
						<element key="order">3</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.journalSettings.checklist.submissionAppearance"}</element>
						<element key="order">4</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.journalSettings.checklist.bibliographicRequirements"}</element>
						<element key="order">5</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.journalSettings.checklist.anonymous"}</element>
						<element key="order">6</element>
					</array>
				</element>
			</array>
		</value>
	</setting>
	<setting type="bool">
		<name>rtAbstract</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtCaptureCite</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtViewMetadata</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtSupplementaryFiles</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtPrinterFriendly</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtAuthorBio</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtDefineTerms</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtAddComment</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtEmailAuthor</name>
		<value>true</value>
	</setting>
	<setting type="bool">
		<name>rtEmailOthers</name>
		<value>true</value>
	</setting>
</journal_settings>
