=== alenoosh/ojs/plugins/importexport/native/native.dtd
<!--
  * native.dtd
  *
  * Copyright (c) 2003-2005 The Public Knowledge Project
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for native XML import/export.
  *
  * $Id$
  -->

<!--
  * BATCH IMPORTING USING OJS 2.x
  *  OJS 2.x supports XML import/export using this plugin for a variety of
  *  base elements:
  *   - article / articles
  *   - issue / issues
  *  Be sure to define the document type appropriately using <!DOCTYPE ...>.
  *
  * Conventions:
  *  - Dates should be specified as MM-DD-YYYY
  -->

<!-- Top-level collection containers for batch importing -->
<!ELEMENT articles (article+)>
<!ELEMENT issues (issue+)>

<!-- Generic elements -->
<!ELEMENT open_access EMPTY>
<!ELEMENT date_published (#PCDATA)>
<!ELEMENT title (#PCDATA)>
	<!-- Note that the locale attribute is currently only supported for
	     article titles and abstracts. -->
	<!ATTLIST title
		locale CDATA #IMPLIED>

<!-- Issue-related elements -->
<!ELEMENT issue (title, description?, volume?, number?, year?, cover?, date_published?, (access_date | open_access)?, section+)>
	<!ATTLIST issue
		published (true|false) "false"
		current (true|false) "false"
		public_id CDATA #IMPLIED>
		
<!ELEMENT cover EMPTY>
	<!ATTLIST cover
		href CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT access_date (#PCDATA)>

<!-- Section-related elements -->
<!ELEMENT section (title, article+)>

<!--
  * Article-related elements
  * NOTES:
  *  - Although this DTD supports unlimited titles and abstracts, OJS 2.x
  *    supports a maximum of 3 of each. These must correspond to the journal's
  *    additional locales, if enabled, otherwise an error will be displayed.
  -->
<!ELEMENT article (title+, abstract*, date_published?, open_access?, author+, (galley?, htmlgalley?)+)>
	<!ATTLIST article
		public_id CDATA #IMPLIED>

<!ELEMENT abstract (#PCDATA)>

<!ELEMENT firstname (#PCDATA)>
<!ELEMENT middlename (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT affiliation (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT biography (#PCDATA)>

<!ELEMENT author (firstname, middlename?, lastname, affiliation?, email?, biography?)>
	<!-- One author should be designated as the primary contact for this
	     article. If no author is designated, the first author with an
	     email address will be used; if multiple authors are designated, the
	     last designated author will be used. The designated author should
	     have a valid email address if possible. -->
	<!ATTLIST author
		primary_contact (true|false) "false">

<!ELEMENT label (#PCDATA)>
<!ELEMENT file EMPTY>
	<!ATTLIST file
		href CDATA #REQUIRED>
<!ELEMENT stylesheet EMPTY>
	<!ATTLIST stylesheet
		href CDATA #REQUIRED>
<!ELEMENT image EMPTY>
	<!ATTLIST image
		href CDATA #REQUIRED>

<!ELEMENT galley (label, file)>
<!ELEMENT htmlgalley (label, file, stylesheet?, image*)>

=== alenoosh/ojs/plugins/importexport/native/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE issues SYSTEM "native.dtd">

<!--
  * sample.xml
  *
  * Copyright (c) 2003-2005 The Public Knowledge Project
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Sample import document for the OJS 2.x native XML import/export format.
  *
  * $Id$
  -->

<issues>
 <issue>
  <title>Test Issue</title>
  <access_date>01-01-2001</access_date>
  <section>
   <title>Articles</title>
   <article>
    <title>Jane Doe's Article</title>
    <author>
     <firstname>Jane</firstname>
     <lastname>Doe</lastname>
    </author>
    <htmlgalley>
     <label>HTML</label>
     <file href="mygalley.html" />
     <stylesheet href="mystylesheet.css" />
     <image href="myimage1.png" />
     <image href="myimage2.png" />
    </htmlgalley>
    <galley>
     <label>PDF</label>
     <file href="mygalley.pdf" />
    </galley>
   </article>
  </section>
 </issue>
 <issue>
  <title>Existingjournal Issue</title>
  <open_access/>
  <section>
   <title>Articles</title>
   <article>
    <title>John Doe's Article</title>
    <author>
     <firstname>John</firstname>
     <lastname>Doe</lastname>
    </author>
   </article>
  </section>
 </issue>
</issues>
